// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopDelivery.Api.Data;

#nullable disable

namespace ShopDelivery.Api.Data.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260720131040_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ShopDelivery.Api.Data.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.CustomerBudget", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerBudgets");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.ImageAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("ImageAssets");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.PriceObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StoreProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("StoreProductId");

                    b.ToTable("PriceObservations");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gtin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MergedIntoProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CatalogKey")
                        .IsUnique()
                        .HasFilter("[CatalogKey] IS NOT NULL");

                    b.HasIndex("Gtin")
                        .IsUnique()
                        .HasFilter("[Gtin] IS NOT NULL");

                    b.HasIndex("MergedIntoProductId");

                    b.HasIndex("NormalizedName", "BrandId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImageAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageAssetId");

                    b.HasIndex("ProductId", "ImageAssetId")
                        .IsUnique();

                    b.HasIndex("ProductId", "IsPrimary");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.ProductReviewItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CandidateProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProposedProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByCustomerIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProductId");

                    b.HasIndex("ProposedProductId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ProductReviewItems");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("CustomerId", "PurchasedAt");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "BranchIdentifier")
                        .IsUnique();

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.StoreProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfirmationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreProductCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("StoreId", "StoreProductCode")
                        .IsUnique()
                        .HasFilter("[StoreProductCode] IS NOT NULL");

                    b.ToTable("StoreProducts");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.StoreProductMatchHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NewProductId");

                    b.HasIndex("PreviousProductId");

                    b.HasIndex("StoreProductId", "CreatedAt");

                    b.ToTable("StoreProductMatchHistory");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.PriceObservation", b =>
                {
                    b.HasOne("ShopDelivery.Api.Data.Product", "Product")
                        .WithMany("PriceObservations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopDelivery.Api.Data.Receipt", "Receipt")
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopDelivery.Api.Data.StoreProduct", "StoreProduct")
                        .WithMany("PriceObservations")
                        .HasForeignKey("StoreProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Product");

                    b.Navigation("Receipt");

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Product", b =>
                {
                    b.HasOne("ShopDelivery.Api.Data.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("ShopDelivery.Api.Data.Product", "MergedIntoProduct")
                        .WithMany()
                        .HasForeignKey("MergedIntoProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("MergedIntoProduct");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.ProductImage", b =>
                {
                    b.HasOne("ShopDelivery.Api.Data.ImageAsset", "ImageAsset")
                        .WithMany("Products")
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopDelivery.Api.Data.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageAsset");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.ProductReviewItem", b =>
                {
                    b.HasOne("ShopDelivery.Api.Data.Product", "CandidateProduct")
                        .WithMany()
                        .HasForeignKey("CandidateProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShopDelivery.Api.Data.Product", "ProposedProduct")
                        .WithMany()
                        .HasForeignKey("ProposedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateProduct");

                    b.Navigation("ProposedProduct");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Receipt", b =>
                {
                    b.HasOne("ShopDelivery.Api.Data.Store", "Store")
                        .WithMany("Receipts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.StoreProduct", b =>
                {
                    b.HasOne("ShopDelivery.Api.Data.Product", "Product")
                        .WithMany("StoreProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopDelivery.Api.Data.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.StoreProductMatchHistory", b =>
                {
                    b.HasOne("ShopDelivery.Api.Data.Product", "NewProduct")
                        .WithMany()
                        .HasForeignKey("NewProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShopDelivery.Api.Data.Product", "PreviousProduct")
                        .WithMany()
                        .HasForeignKey("PreviousProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShopDelivery.Api.Data.StoreProduct", "StoreProduct")
                        .WithMany("History")
                        .HasForeignKey("StoreProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewProduct");

                    b.Navigation("PreviousProduct");

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.ImageAsset", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PriceObservations");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Receipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.Store", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("ShopDelivery.Api.Data.StoreProduct", b =>
                {
                    b.Navigation("History");

                    b.Navigation("PriceObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
